function answer = cameraBackgroundSettingsDlg(mainhandle,DefAns)
% cameraBackgroundSettingsDlg creates a modal dialog box that returns user
% input for multiple prompts in the cell array ANSWER.
% cameraBackgroundSettingsDlg uses UIWAIT to suspend execution until the
% user responds.
%
%    Input:
%     mainhandle   - handle to the main figure window (sms)
%     DefAns       - default answers structure
%
%    Output:
%     answer       - structure matching DefAns with users answers
%

% --- Copyrights (C) ---
%
% This file is part of:
% iSMS - Single-molecule FRET microscopy software
% Copyright (C) Aarhus University, @ V. Birkedal Lab
% <http://isms.au.dk>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     The GNU General Public License is found at
%     <http://www.gnu.org/licenses/gpl.html>.

%% Initialize

answer = [];

% Check number of input arguments
if (isempty(mainhandle)) || (~ishghandle(mainhandle))
    return
end
mainhandles = guidata(mainhandle); % Get mainhandles structure

%% Create GUI window

h.figure1 = dialog(...
    'Name',     'Camera background settings',...
    'Units',    'pixels',...
    'Position', [520  536  490  266],...
    'Visible',  'off',...
    'UserData', 'Cancel');
movegui(h.figure1,'center')
updatelogo(h.figure1) % Update logo

%--------- Create GUI components ---------%
% Panel
h.obsPanel = uipanel(...
    'Parent',   h.figure1,...
    'Title',   'OBS: ',...
    'Units',    'pixels',...
    'position', [8 162 472 94]);

% Textbox
h.obsTextbox1 = uicontrol(...
    'Parent',   h.obsPanel,...
    'Style',    'text',...
    'String',   'The chosen camera background is automatically subtracted upon loading the movie',...
    'HorizontalAlignment',   'left',...
    'Units',    'pixels',...
    'position', [15 55 433  15]);
% Textbox
h.obsTextbox2 = uicontrol(...
    'Parent',   h.obsPanel,...
    'Style',    'text',...
    'String',   'and can''t be changed afterwards, unless reloading the movie with the new settings.',...
    'HorizontalAlignment',   'left',...
    'Units',    'pixels',...
    'position', [15 30 427 20]);
% Textbox
h.obsTextbox3 = uicontrol(...
    'Parent',   h.obsPanel,...
    'Style',    'text',...
    'String',   'All pixels resulting in negative values will be assigned 0. ',...
    'HorizontalAlignment',   'left',...
    'Units',    'pixels',...
    'position', [15 15 286 15]);


% Textbox
h.choiceTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Camera background (subtracted when loading the movie): ',...
    'Units',    'pixels',...
    'HorizontalAlignment', 'left',...
    'Position', [16  133  297  15]...
    );
% Popupmenu
h.choicePopupmenu = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'popupmenu',...
    'String',   {'Subtract raw background image from all frames (if present in loaded file)',...
                 'Subtract smoothened background image from all frames (if present in loaded file)',...
                 'Subtract averaged background image value from all pixels (if present in loaded file)',...
                 'Subtract constant offset/baseline value',...
                 'Don''t subtract camera background'},...
    'Value',    DefAns.choice,...
    'Units',    'pixels',...
    'Position', [16 105 451 20],...
    'BackgroundColor',  'white'...
    );


% Textbox (dynamic)
h.dynamicTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Kernel size: ',...
    'HorizontalAlignment',   'left',...
    'Units',    'pixels',...
    'position', [21 76 132 15]);
% Editbox/popupmenu (dynamic)
h.dynamicBox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'edit',...
    'String',   '',...
    'Units',    'pixels',...
    'Position', [162 76 93 20],...
    'BackgroundColor',  'white'...
    );


% Checkbox
h.checkOffsetCheckbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'check',...
    'String',   'Check if background exceeds the count in >50% of the pixels (increases loading time)',...
    'Value',    0,...
    'Enable',   'on',...
    'Units',    'pixels',...
    'Position', [21 46  460 23]...
    );


%-- OK pushbutton --%
h.OKpushbutton = uicontrol(...
    'Parent',   h.figure1,...
    'String',   'OK',...
    'Style',    'pushbutton',...
    'Units',    'pixels',...
    'Position', [385 12 78 26]...
    );

%-- Cancel pushbutton --%
h.CancelPushbutton = uicontrol(...
    'Parent',   h.figure1,...
    'String',   'Cancel',...
    'Style',    'pushbutton',...
    'Units',    'pixels',...
    'Position', [299 12 78 26]...
    );

%-- Cancel pushbutton --%
h.helpPushbutton = uicontrol(...
    'Parent',   h.figure1,...
    'String',   ' More information ',...
    'Style',    'pushbutton',...
    'Units',    'pixels',...
    'Position', [21 12 120 26]...
    );

%% Set callbacks

set(h.choicePopupmenu,'Callback',{@updateGUI, h}); % Assign callback
set(h.OKpushbutton,'Callback',{@pushbutton_Callback, h}); % Assign callback
set(h.CancelPushbutton,'Callback',{@pushbutton_Callback, h}); % Assign callback
set(h.helpPushbutton,'callback',{@panelHelpFcn, 'http://isms.au.dk/documentation/camera-background/'})

%% Update dialog

guidata(h.figure1,h)
updateGUI([],[],h)
set(h.figure1,'Visible','on')

% For closing the figure
if ishghandle(h.figure1)
  % Go into uiwait if the figure handle is still valid.
  % This is mostly the case during regular use.
  uiwait(h.figure1);
end

%% This code hereafter is only run once uiresume is called
% Check handle validity again since we may be out of uiwait because the
% figure was deleted.
if ishghandle(h.figure1)
  if strcmp(get(h.figure1,'UserData'),'OK')
      answer.choice = get(h.choicePopupmenu,'Value'); % How intensity is calculated. 1 = sum pixel values. 2 = 2D Gaussian fit.
      answer.dynamic = [];
      if answer.choice == 2 % If smoothing background
          answer.dynamic = get(h.dynamicBox,'value');
      elseif answer.choice == 4 % If using manual offset
          answer.dynamic = str2num(get(h.dynamicBox,'String'));
      end
      answer.checkOffset = get(h.checkOffsetCheckbox,'Value');  
  end
  delete(h.figure1);
else
  answer = [];
end

%-----------------------------------------------------------%
%-----------------------------------------------------------%
%-----------------------------------------------------------%

function pushbutton_Callback(hObject,eventdata,h) %% Callback for pressing either 'Cancel' or 'OK'
if ~strcmp(get(hObject,'String'),'Cancel')
    set(gcbf,'UserData','OK');
    uiresume(gcbf);
else
    delete(gcbf)
end

function updateGUI(Object,eventdata,h) %% Updates the visibility of the individual GUI components depending on the selection choices
mainhandles = guidata(getappdata(0,'mainhandle'));

h_temp = [h.dynamicTextbox  h.dynamicBox];

% Check intensity type
typechoice = get(h.choicePopupmenu,'Value');
if (typechoice==1) || typechoice==3 || typechoice==5
    set(h_temp,'Visible','off')
else
    set(h_temp,'Visible','on')    
end

if typechoice==3 || typechoice==4
    set(h.checkOffsetCheckbox,'Visible','on')
    set(h.checkOffsetCheckbox,'Value',mainhandles.settings.background.checkOffset)
else
    set(h.checkOffsetCheckbox,'Visible','off')
end

% Set dynamic box
if typechoice==2 % If smoothing background image
    set(h.dynamicTextbox,'String','Kernel size (pixels): ')
    set(h.dynamicBox,'Style','popupmenu')
    set(h.dynamicBox,'String',{'3x3'; '5x5'; '7x7'; '9x9'; '15x15'})
    set(h.dynamicBox,'Value',mainhandles.settings.background.smthKernel)

elseif typechoice==4 % If subtracting manual offset
    set(h.dynamicTextbox,'String','Offset/baseline (counts): ')
    set(h.dynamicBox,'Style','edit')
    set(h.dynamicBox,'String',mainhandles.settings.background.cameraOffset)
end
