function mainhandles = peakfinderSettingsCallback(mainhandles)
% Callback for the peakfinder settings menu
%
%     Input:
%      mainhandles    - handles structure of the main window
%
%     Output:
%      mainhandles    - ..
%

% --- Copyrights (C) ---
%
% This file is part of:
% iSMS - Single-molecule FRET microscopy software
% Copyright (C) Aarhus University, @ V. Birkedal Lab
% <http://isms.au.dk>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     The GNU General Public License is found at
%     <http://www.gnu.org/licenses/gpl.html>.

%% Initialize

% GUI scales /pixels
space = 5;
buttonwidth = 70;
buttonheight = 30;
editwidth = 62;
editheight = 22;
textheight = 17;
popupheight = 20;
checkheight = 22;
tabwidth = 60;
tabheight = 4*space;

nelements = 21;
guiheight = space+buttonheight + nelements*space + nelements*editheight + 4*tabheight;
guiwidth = 410;
checkwidth = guiwidth-2*space;

% Mainhandles structure
if nargin<1
    mainhandles = guidata(getappdata(0,'mainhandle'));
end
mainhandles = turnofftoggles(mainhandles,'all');% Turn off all interactive toggle buttons in the toolbar

%% Create modal dialog window

h.figure1 = dialog(...
    'Name',     'Peak-finder settings',...
    'Units',    'normalized',...
    'Visible',  'off',...
    'UserData', 'Cancel');
setpixelposition(h.figure1,[1 1 guiwidth guiheight])
movegui(h.figure1,'center') % Centerize
updatelogo(h.figure1) % Update logo

% Textbox
h.DpeakIntensityThresholdTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Default D peak intensity threshold (peak count - background): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.DpeakIntensityThresholdEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.DpeakIntensityThreshold,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.ApeakIntensityThresholdTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Default A peak intensity threshold (peak count - background): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.ApeakIntensityThresholdEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.ApeakIntensityThreshold,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.DthresholdTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Threshold for max. D peaks (0-1, lower value->more peaks): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.DthresholdEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.Dthreshold,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.AthresholdTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Threshold for max. A peaks (0-1, lower value->more peaks): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.AthresholdEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.Athreshold,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.maxpeaksTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Max. number of peaks ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.maxpeaksEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.maxpeaks,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Checkbox
h.subpixelCheckbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'check',...
    'String',   'Use sub-pixel localization (using local centroids; uncheck for dense samples) ',...
    'Value',    mainhandles.settings.peakfinder.subpixel...
    );

% Textbox
h.EcriteriaTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Max. D-A peak separation when identifying a FRET-pair  /pixels: ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.EcriteriaEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.Ecriteria,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Checkbox
h.liveupdateFRETpairsCheckbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'check',...
    'String',   'Auto-update FRET pairs when moving peak sliders ',...
    'Value',    mainhandles.settings.peakfinder.liveupdateFRETpairs...
    );

% Textbox
h.intensityTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'The peak finder sorts peaks according to intensity: ',...
    'HorizontalAlignment',   'left'...
    );
% Checkbox
h.useBackCheckbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'check',...
    'String',   'Use background subtraction',...
    'Value',    mainhandles.settings.peakfinder.useBack...
    );
% Checkbox
h.useSpotCheckbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'check',...
    'String',   'Use spot profile weighting (when a laser spot profile is defined)',...
    'Value',    mainhandles.settings.peakfinder.useSpot...
    );

% Textbox
h.peakfinderTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Peak finder choice: ',...
    'HorizontalAlignment',   'left'...
    );
% Popupmenu
h.peakfinderPopupmenu = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'popupmenu',...
    'String',   {'Find peaks in selected image/frame',...
    'Find peaks by scanning movie'},...
    'Value',    mainhandles.settings.peakfinder.choice,...
    'BackgroundColor',  'white'...
    );

% Textbox
h.avgFramesTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Average neighbouring frames at each step: ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.avgFramesEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.avgFrames,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.stepsizeTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Step size (frames): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.stepsizeEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.stepsize,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.scanpercTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Scan % of movie (0-1): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.scanpercEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.scanperc,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.distCriteriaTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Remove peaks closer than (pixels): ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.distCriteriaEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.distCriteria,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.DsliderInternalTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Internal D peak slider value at each step: ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.DsliderInternalEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.DsliderInternal,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Textbox
h.AsliderInternalTextbox = uicontrol(...
    'Parent',   h.figure1,...
    'Style',    'text',...
    'String',   'Internal A peak slider value at each step: ',...
    'HorizontalAlignment',   'left'...
    );
% Editbox
h.AsliderInternalEditbox = uicontrol(...
    'Parent',   h.figure1,...
    'String',   mainhandles.settings.peakfinder.AsliderInternal,...
    'Style',    'edit',...
    'BackgroundColor',  'white'...
    );

% Checkbox
h.DatAcheck = uicontrol(...
    'Parent', h.figure1,...
    'String', 'Put a D at every A position (for high FRET)',...
    'Style', 'check',...
    'Value', mainhandles.settings.peakfinder.DatA);

% Checkbox
h.AatDcheck = uicontrol(...
    'Parent', h.figure1,...
    'String', 'Put an A at every D position (for low FRET)',...
    'Style', 'check',...
    'Value', mainhandles.settings.peakfinder.AatD);

%-- OK pushbutton --%
h.OKpushbutton = uicontrol(...
    'Parent',   h.figure1,...
    'String',   'OK',...
    'Style',    'pushbutton');

%-- Cancel pushbutton --%
h.CancelPushbutton = uicontrol(...
    'Parent',   h.figure1,...
    'String',   'Cancel',...
    'Style',    'pushbutton'...
    );

%% Set positions

vpos = space;
setpixelposition(h.OKpushbutton, [guiwidth-space-buttonwidth space buttonwidth buttonheight])
setpixelposition(h.CancelPushbutton, [guiwidth-2*space-2*buttonwidth space buttonwidth buttonheight])

vpos = vpos + tabheight+buttonheight;
setpixelposition(h.AatDcheck, [space vpos checkwidth checkheight]);

vpos = vpos + space+checkheight;
setpixelposition(h.DatAcheck, [space vpos checkwidth checkheight]);

vpos = vpos + tabheight+checkheight;
hpos1 = space+tabwidth;
hpos2 = guiwidth-space-editwidth;
w = (guiwidth-2*space-editwidth)-(space+tabwidth);
setpixelposition(h.AsliderInternalTextbox, [hpos1 vpos w textheight])
setpixelposition(h.AsliderInternalEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.DsliderInternalTextbox, [hpos1 vpos w textheight])
setpixelposition(h.DsliderInternalEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.distCriteriaTextbox, [hpos1 vpos w textheight])
setpixelposition(h.distCriteriaEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.scanpercTextbox, [hpos1 vpos w textheight])
setpixelposition(h.scanpercEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.stepsizeTextbox, [hpos1 vpos w textheight])
setpixelposition(h.stepsizeEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.avgFramesTextbox, [hpos1 vpos w textheight])
setpixelposition(h.avgFramesEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+2*space+editheight;
setpixelposition(h.peakfinderTextbox, [space vpos 105 textheight])
setpixelposition(h.peakfinderPopupmenu, [2*space+105 vpos guiwidth-space-(2*space+105) popupheight])


vpos = vpos+tabheight+popupheight;
setpixelposition(h.useSpotCheckbox, [space+tabwidth vpos guiwidth-space-(space+tabwidth) checkheight])

vpos = vpos+space+checkheight;
setpixelposition(h.useBackCheckbox, [space+tabwidth vpos guiwidth-space-(space+tabwidth) checkheight])

vpos = vpos+space+checkheight;
setpixelposition(h.intensityTextbox, [space vpos guiwidth-2*space textheight])


vpos = vpos+tabheight+textheight;
setpixelposition(h.liveupdateFRETpairsCheckbox, [tabwidth vpos guiwidth-2*space checkheight])

vpos = vpos+space+checkheight;
w = guiwidth-3*space-editwidth;
setpixelposition(h.EcriteriaTextbox, [space vpos w textheight])
setpixelposition(h.EcriteriaEditbox, [hpos2 vpos editwidth editheight])


vpos = vpos+tabheight+editheight;
setpixelposition(h.subpixelCheckbox, [space vpos guiwidth-2*space checkheight])


vpos = vpos+tabheight+editheight;
setpixelposition(h.maxpeaksTextbox, [space vpos w textheight])
setpixelposition(h.maxpeaksEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.AthresholdTextbox, [space vpos w textheight])
setpixelposition(h.AthresholdEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.DthresholdTextbox, [space vpos w textheight])
setpixelposition(h.DthresholdEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+tabheight+editheight;
setpixelposition(h.ApeakIntensityThresholdTextbox, [space vpos w textheight])
setpixelposition(h.ApeakIntensityThresholdEditbox, [hpos2 vpos editwidth editheight])

vpos = vpos+space+editheight;
setpixelposition(h.DpeakIntensityThresholdTextbox, [space vpos w textheight])
setpixelposition(h.DpeakIntensityThresholdEditbox, [hpos2 vpos editwidth editheight])

%% Set callbacks

hs = [h.DpeakIntensityThresholdEditbox h.ApeakIntensityThresholdEditbox...
    h.DthresholdEditbox h.AthresholdEditbox h.maxpeaksEditbox h.EcriteriaEditbox...
    h.avgFramesEditbox h.stepsizeEditbox h.scanpercEditbox ...
    h.peakfinderPopupmenu h.distCriteriaEditbox h.DsliderInternalEditbox ...
    h.AsliderInternalEditbox];
set(hs,'Callback',{@updateGUI, h}); % Assign callback

set(h.OKpushbutton,'Callback',{@pushbutton_Callback, h}); % Assign callback
set(h.CancelPushbutton,'Callback',{@pushbutton_Callback, h}); % Assign callback

%--- Update dialog ---%
guidata(h.figure1,h)
updateGUI([],[],h)
set(h.figure1,'Visible','on')

%% Go into uiwait if the figure handle is still valid.

if ishghandle(h.figure1)
    uiwait(h.figure1);
end

%% This code hereafter is only run once uiresume is called

% Check handle validity again since we may be out of uiwait because the
% figure was deleted.
if ishghandle(h.figure1)
    if strcmp(get(h.figure1,'UserData'),'OK')
        
        % Settings
        DpeakIntensityThreshold = str2num(get(h.DpeakIntensityThresholdEditbox,'String'));
        ApeakIntensityThreshold = str2num(get(h.ApeakIntensityThresholdEditbox,'String'));
        Dthreshold = str2num(get(h.DthresholdEditbox,'String'));
        Athreshold = str2num(get(h.AthresholdEditbox,'String'));
        Ecriteria = abs(str2num(get(h.EcriteriaEditbox,'String')));
        liveupdateFRETpairs = get(h.liveupdateFRETpairsCheckbox,'Value');
        maxpeaks = round(abs(str2num(get(h.maxpeaksEditbox,'String'))));
        subpixel = get(h.subpixelCheckbox,'Value');
        
        useBack = get(h.useBackCheckbox,'Value');
        useSpot = get(h.useSpotCheckbox,'Value');
        choice = get(h.peakfinderPopupmenu,'Value');
        avgFrames = str2num(get(h.avgFramesEditbox,'String'));
        stepsize = str2num(get(h.stepsizeEditbox,'String'));
        scanperc = str2num(get(h.scanpercEditbox,'String'));
        distCriteria = str2num(get(h.distCriteriaEditbox,'String'));
        DsliderInternal = str2num(get(h.DsliderInternalEditbox,'String'));
        AsliderInternal = str2num(get(h.AsliderInternalEditbox,'String'));
        
        DatA = get(h.DatAcheck,'Value');
        AatD = get(h.AatDcheck,'Value');
        
        % Save settings
        mainhandles = savesettingasDefaultDlg(mainhandles,...
            'peakfinder',...
            {'DpeakIntensityThreshold' 'ApeakIntensityThreshold' 'Dthreshold' 'Athreshold'...
            'Ecriteria' 'liveupdateFRETpairs' 'maxpeaks' 'subpixel'...
            'useBack' 'useSpot' 'choice' 'avgFrames'...
            'stepsize' 'scanperc' 'distCriteria' 'DsliderInternal'...
            'AsliderInternal' 'DatA' 'AatD'},...
            {DpeakIntensityThreshold ApeakIntensityThreshold Dthreshold Athreshold...
            Ecriteria liveupdateFRETpairs maxpeaks subpixel...
            useBack useSpot choice avgFrames...
            stepsize scanperc distCriteria DsliderInternal...
            AsliderInternal DatA AatD});
        
    end
    delete(h.figure1);
else
    return
end

% Update handles structure
updatemainhandles(mainhandles)

% Update the peakfinder panel
mainhandles = updatePeakthresholdsEditbox(mainhandles,2);

if isempty(mainhandles.data)
    return
end

%% Check if re-run peak finder

filechoice = [];

% Check if peaks have already been found in any of the files
for i = 1:length(mainhandles.data)
    if ~isempty(mainhandles.data(i).ApeaksRaw) || ~isempty(mainhandles.data(i).DpeaksRaw)
        
        % Dialog
        choice = myquestdlg('Do you wish to run the peak finder with the new settings? This will remove any previous FRET pairs.',...
            'Run peak finder',...
            ' Yes, for current selected file ',' Yes, for all loaded files ','No',' Yes, for current selected file ');
        
        % Files to re-analyse
        if strcmpi(choice,'Yes, for current selected file')
            filechoice = get(mainhandles.FilesListbox,'Value');
        elseif strcmpi(choice,'Yes, for all loaded files')
            filechoice_prev = get(mainhandles.FilesListbox,'Value');
            filechoice = 1:length(mainhandles.data);
        end
        
        break
    end
end

%% Update

% Reset raw peaks, this will force a new peak run on the selected frame
for i = 1:length(mainhandles.data)
    mainhandles.data(i).DpeaksRaw = [];
    mainhandles.data(i).ApeaksRaw = [];
end

% Update handle structure before running peakfinder
updatemainhandles(mainhandles)

% Run peakfinder
for i = filechoice(:)'
    if length(filechoice)>1
        set(mainhandles.FilesListbox,'Value',i)
        mainhandles = filesListboxCallback(mainhandles.FilesListbox); % Imitate click in listbox
    end
    
    set(mainhandles.DPeakSlider,'Value',0) % Reset slider values
    set(mainhandles.APeakSlider,'Value',0) % Reset slider values
    mainhandles = clearpeaksdata(mainhandles,i);
    updatemainhandles(mainhandles)
    mainhandles = findEpairsCallback(mainhandles, 0);
    mainhandles = guidata(mainhandles.figure1);
end

% Set files listbox value back to original
if length(filechoice)>1
    set(mainhandles.FilesListbox,'Value',filechoice_prev)
end

% Update handles structure one final time
updatemainhandles(mainhandles)

end

function pushbutton_Callback(hObject,eventdata,h) %%
if ~strcmp(get(hObject,'String'),'Cancel')
    set(gcbf,'UserData','OK');
    uiresume(gcbf);
else
    delete(gcbf)
end

end

function updateGUI(Object,eventdata,h) %% Updates the visibility of the individual GUI components depending on the selection choices
h_temp = [h.avgFramesTextbox h.stepsizeTextbox h.scanpercTextbox h.avgFramesEditbox h.stepsizeEditbox h.scanpercEditbox...
    h.distCriteriaTextbox h.distCriteriaEditbox h.DsliderInternalTextbox h.DsliderInternalEditbox h.AsliderInternalTextbox h.AsliderInternalEditbox];

% Check handle visibilities
if get(h.peakfinderPopupmenu,'Value')==1
    set(h_temp,'Enable','off')
elseif get(h.peakfinderPopupmenu,'Value')==2
    set(h_temp,'Enable','on')
end

% Check editbox values
% Dslider = str2num(get(h.DsliderEditbox,'String'));
% Aslider = str2num(get(h.AsliderEditbox,'String'));
DpeakIntensityThreshold = str2num(get(h.DpeakIntensityThresholdEditbox,'String'));
ApeakIntensityThreshold = str2num(get(h.ApeakIntensityThresholdEditbox,'String'));
Dthreshold = str2num(get(h.DthresholdEditbox,'String'));
Athreshold = str2num(get(h.AthresholdEditbox,'String'));
maxpeaks = str2num(get(h.maxpeaksEditbox,'String'));
Ecriteria = str2num(get(h.EcriteriaEditbox,'String'));
avgFrames = str2num(get(h.avgFramesEditbox,'String'));
stepsize = str2num(get(h.stepsizeEditbox,'String'));
scanperc = str2num(get(h.scanpercEditbox,'String'));
distCriteria = str2num(get(h.distCriteriaEditbox,'String'));
DsliderInternal = str2num(get(h.DsliderInternalEditbox,'String'));
AsliderInternal = str2num(get(h.AsliderInternalEditbox,'String'));
if DpeakIntensityThreshold<1
    set(h.DpeakIntensityThresholdEditbox,'String', 1);
end
if ApeakIntensityThreshold<1
    set(h.ApeakIntensityThresholdEditbox,'String', 1);
end
if Dthreshold<0
    set(h.DthresholdEditbox,'String',0)
elseif Dthreshold>1
    set(h.DthresholdEditbox,'String',1)
end
if Athreshold<0
    set(h.AthresholdEditbox,'String',0)
elseif Athreshold>1
    set(h.AthresholdEditbox,'String',1)
end
if maxpeaks<1
    set(h.maxpeaksEditbox,'String',1)
end
if Ecriteria<0
    set(h.EcriteriaEditbox,'String',0)
end
if avgFrames<1
    set(h.avgFramesEditbox,'String',1)
end
if stepsize<1
    set(h.stepsizeEditbox,'String',1)
end
if scanperc<0
    set(h.scanpercEditbox,'String',0)
elseif scanperc>1
    set(h.scanpercEditbox,'String',1)
end
if distCriteria<1
    set(h.distCriteriaEditbox,'String',1)
end
if DsliderInternal<0
    set(h.DsliderInternalEditbox,'String', 0);
elseif DsliderInternal>1
    set(h.DsliderInternalEditbox,'String', 1);
end
if AsliderInternal<0
    set(h.AsliderInternalEditbox,'String', 0);
elseif AsliderInternal>1
    set(h.AsliderInternalEditbox,'String', 1);
end
end