function [allFormatsList, imageFormats, movieFormats, bioFormats, specialFormats] = supportedformatsImport(~)
% Returns file formats supported for import
%
%    Input:
%     None
%
%    Output:
%     allFormatsList   - Combined cell array used for file dialog box
%     movieformats     - cell array with movie formats
%     bioformats       - cell array with bioformats (i.e. opened by bfopen)
%     specialformats   - cell array with special formats (.sif, .spe, etc)
%

% --- Copyrights (C) ---
%
% This file is part of:
% iSMS - Single-molecule FRET microscopy software
% Copyright (C) Aarhus University, @ V. Birkedal Lab
% <http://isms.au.dk>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     The GNU General Public License is found at
%     <http://www.gnu.org/licenses/gpl.html>.

%% Formats

% img formats
imageFormats = {...
    '*.bmp', 'Windows Bitmap';...
    '*.cur', 'Windows Cursor resources';...
    '*.gif', 'Graphics Interchange Format';...
    '*.hdf', 'Hierarchical Data Format';...
    '*.ico', 'Windows Icon Resource';...
    '*.jpf;*.jpx;*.jp2;*.j2c;*.j2k', 'JPEG 2000';...
    '*.jpg;*.jpeg', 'Joint Photographic Experts Group';...
    '*.pbm', 'Portable Bitmap';...
    '*.pcx', 'Windows Paintbrush';...
    '*.pgm', 'Portable Graymap';...
    '*.png', 'Portable Network Graphics';...
    '*.pnm', 'Portable Any Map';...
    '*.ppm', 'Portable Pixmap';...
    '*.ras', 'Sun Raster';...
    '*.tif;*.tiff', 'Tagged Image File Format';...
    '*.xwd', 'X Windows Dump'};
imageFormats = sortrows(imageFormats,2);

% mov formats
movieFormats = {...
    '*.avi', 'AVI file';...
    '*.mj2', 'Motion JPEG 2000';...
    '*.mpg', 'MPEG-1';...
    '*.mp4;*.m4v', 'MPEG-4';...
    '*.mov', 'Apple Quicktime Movie';...
    '*.avi', 'AVI file';...
    '*.mj2', 'Motion JPEG 2000';...
    '*.mpg', 'MPEG-1';...
    '*.mp4;*.m4v', 'MPEG-4';...
    '*.mov', 'Apple Quicktime Movie';...
    '*.wmv;*.asf;*.asx', 'Windows Media Video'...
    };
if ismac
    % Mac does not support windows formats
%     movieFormats(end) = [];
end
movieFormats = sortrows(movieFormats,2);

% bio-formats opened by bfopen from the open microscopy foundation
bioFormats = {...
	'*.sld', '3i SlideBook';...
	'*.tif', 'Andor Bio-Imaging Division (ABD) TIFF';...
	'*.aim', 'AIM';...
	'*.al3d', 'Alicona 3D';...
	'*.gel', 'Amersham Biosciences Gel';...
	'*.am;*.amiramesh;*.grey;*.hx;*.labels', 'Amira Mesh';...
	'*.img;*.hdr', 'Analyze 7.5';...
	'*.png', 'Animated PNG';...
	'*.svs', 'Aperio SVS TIFF';...
	'*.htd;*.pnl', 'Applied Precision CellWorX';...
	'*.avi', 'AVI (Audio Video Interleave)';...
	'*.arf', 'Axon Raw Format';...
	'*.exp;*.tif', 'BD Pathway';...
	'*.sdt', 'Becker & Hickl SPCImage';...
	'*.1sc', 'Bio-Rad Gel';...
	'*.pic;*.raw;*.xml', 'Bio-Rad PIC';...
	'*.ims', 'Bitplane Imaris';...
	'*.ims', 'Bruker MRI';...
	'*.img', 'Burleigh';...
	'*.cr2;*.crw', 'Canon DNG';...
	'*.c01', 'Cellomics';...
	'*.vsi', 'cellSens VSI';...
	'*.dv;*.r3d', 'DeltaVision';...
	'*.dcm;*.dicom', 'DICOM';...
	'*.v', 'ECAT7';...
	'*.eps;*.epsi;*.ps', 'EPS (Encapsulated PostScript)';...
	'*.flex;*.mea;*.res', 'Evotec/PerkinElmer Opera Flex';...
	'*.img', 'FEI';...
	'*.tiff', 'FEI TIFF';...
	'*.fits', 'FITS (Flexible Image Transport System)';...
	'*.dm3', 'Gatan Digital Micrograph';...
	'*.dm2', 'Gatan Digital Micrograph 2';...
	'*.gif', 'GIF (Graphics Interchange Format)';...
	'*.naf', 'Hamamatsu Aquacosmos NAF';...
	'*.his', 'Hamamatsu HIS';...
	'*.ndpi', 'Hamamatsu ndpi';...
	'*.vms', 'Hamamatsu VMS';...
	'*.txt;*.tif;*.bmp;*.jpg', 'Hitachi S-4800';...
	'*.ics;*.ids', 'ICS (Image Cytometry Standard)';...
	'*.fff', 'Imacon';...
	'*.seq', 'ImagePro Sequence';...
	'*.ipw', 'ImagePro Workspace';...
	'*.hed;*.img', 'IMAGIC';...
	'*.mod', 'IMOD';...
	'*.liff', 'Improvision Openlab LIFF';...
	'*.raw', 'Improvision Openlab Raw';...
	'*.tif', 'Improvision TIFF';...
	'*.xdce;*.tif', 'InCell 1000';...
	'*.frm', 'InCell 3000';...
	'*.inr', 'INR';...
	'*.ipl', 'IPLab';...
	'*.ipm', 'IPLab-Mac';...
	'*.dat;*.img;*.par', 'JEOL';...
	'*.jpg', 'JPEG';...
	'*.jp2', 'JPEG 2000';...
	'*.jpk', 'JPK';...
	'*.jpx', 'JPX';...
	'*.xv', 'Khoros VIFF (Visualization Image File Format) Bitmap';...
	'*.bip', 'Kodak BIP';...
	'*.fli', 'Lambert Instruments FLIM';...
	'*.lei;*.tif', 'Leica LCS LEI';...
	'*.lif', 'Leica LAS AF LIF (Leica Image File Format)';...
	'*.scn', 'Leica SCN';...
	'*.sxm', 'LEO';...
	'*.l2d;*.tif;*.scn', 'Li-Cor L2D';...
	'*.lim', 'LIM (Laboratory Imaging/Nikon)';...
	'*.tiff', 'MetaMorph 7.5 TIFF';...
	'*.stk;*.nd', 'MetaMorph Stack (STK)';...
	'*.tif', 'MIAS (Maia Scientific)';...
	'*.tif;*.txt;*.xml', 'Micro-Manager';...
	'*.mnc', 'MINC MRI';...
	'*.mrw', 'Minolta MRW';...
	'*.mng', 'MNG (Multiple-image Network Graphics)';...
	'*.stp', 'Molecular Imaging';...
	'*.mrc', 'MRC (Medical Research Council)';...
	'*.nef;*.tif', 'NEF (Nikon Electronic Format)';...
	'*.img;*.hdr', 'NIfTI';...
	'*.tiff', 'Nikon Elements TIFF';...
	'*.tiff', 'Nikon EZ-C1 TIFF';...
	'*.nd2', 'Nikon NIS-Elements ND2';...
	'*.nrrd;*.nhdr;*.raw;*.txt', 'NRRD (Nearly Raw Raster Data)';...
	'*.apl;*.mtb;*.tnb;*.tif;*.obsep', 'Olympus CellR/APL';...
	'*.oib;*.oif', 'Olympus FluoView FV1000';...
	'*.tif', 'Olympus FluoView TIFF';...
	'*.xml;*.dat;*.tif', 'Olympus ScanR';...
	'*.tiff', 'Olympus SIS TIFF';...
	'*.ome.tiff', 'OME-TIFF';...
	'*.ome', 'OME-XML';...
	'*.top', 'Oxford Instruments';...
	'*.pcx', 'PCX (PC Paintbrush)';...
	'*.pds', 'Perkin Elmer Densitometer';...
	'*.tiff;*.xml', 'PerkinElmer Operetta';...
	'*.tif;*.2;*.3;*.4;*.tim;*.zpo;*.csv;*.htm;*.cfg;*.ano;*.rec', 'PerkinElmer UltraView';...
	'*.pgm', 'PGM (Portable Gray Map)';...
	'*.psd', 'Adobe Photoshop PSD';...
	'*.tif;*.tiff', 'Photoshop TIFF';...
	'*.pict', 'PICT (Macintosh Picture)';...
	'*.png', 'PNG (Portable Network Graphics)';...
	'*.tif;*.xml;*.cfg', 'Prairie Technologies TIFF';...
	'*.afm', 'Quesant';...
	'*.mov', 'QuickTime Movie';...
	'*.sm2;*.sm3', 'RHK';...
	'*.sm2;*.sm3', 'SBIG';...
	'*.xqd;*.xqf', 'Seiko';...
	'*.cxd', 'SimplePCI & HCImage';...
	'*.tiff', 'SimplePCI & HCImage TIFF';...
	'*.tiff', 'SM Camera';...
	'*.spi;*.stk', 'SPIDER';...
	'*.tga', 'Targa';...
	'*.txt', 'Text';...
	'*.tif', 'TIFF (Tagged Image File Format)';...
	'*.vws', 'TillPhotonics TillVision';...
	'*.tfr;*.ffr;*.zfr;*.zfp;*.2fl', 'Topometrix';...
	'*.tif;*.sld;*.jpg', 'Trestle';...
	'*.pr3', 'UBM';...
	'*.dat;*.hdr', 'Unisoku';...
	'*.fdf', 'Varian FDF';...
	'*.dti', 'VG SAM';...
	'*.xys;*.html', 'VisiTech XYS';...
	'*.mvd2', 'Volocity';...
	'*.acff', 'Volocity Library Clipping';...
	'*.wat', 'WA-TOP';...
	'*.bmp', 'Windows Bitmap';...
	'*.xml;*.tiff', 'Zeiss AxioVision TIFF';...
	'*.zvi', 'Zeiss AxioVision ZVI (Zeiss Vision Image)';...
	'*.czi', 'Zeiss CZI';...
	'*.lsm;*.mdb', 'Zeiss LSM (Laser Scanning Microscope) 510/710'};
bioFormats = sortrows(bioFormats,2);

% special formats
specialFormats = {...
    '*.fts;*.fits', 'Flexible Image Transport System';...
    '*.sif', 'Andor Camera File';...
    '*.spe', 'Princeton Instruments File v2+'};
specialFormats = sortrows(specialFormats,2);

%% Process string arrays

% all file formats
temp = cellfun(@(x) strrep(x,';*.','*.'), imageFormats(:,1),'UniformOutput',false);
imgcompr = cellfun(@(x) strrep(x,'*.',';*.'), temp,'UniformOutput',false);
imgcompr = [imgcompr{:}];
imgcompr(1) = []; % Remove the first ';'

temp = cellfun(@(x) strrep(x,';*.','*.'), movieFormats(:,1),'UniformOutput',false);
movcompr = cellfun(@(x) strrep(x,'*.',';*.'), temp,'UniformOutput',false);
movcompr = [movcompr{:,1}];

temp = cellfun(@(x) strrep(x,';*.','*.'), bioFormats(:,1),'UniformOutput',false);
biocompr = cellfun(@(x) strrep(x,'*.',';*.'), temp,'UniformOutput',false);
biocompr = [biocompr{:,1}];

temp = cellfun(@(x) strrep(x,';*.','*.'), specialFormats(:,1),'UniformOutput',false);
specompr = cellfun(@(x) strrep(x,'*.',';*.'), temp,'UniformOutput',false);
specompr = [specompr{:,1}];

% allformats = {[[imgcompr{:}] [movcompr{:,1}] [biocompr{:,1}] [speccompr{:,1}]],  'All Image and Movie Files'};
allformats = {sprintf('%s%s%s%s',imgcompr, movcompr, biocompr, specompr),  'All Image and Movie Files'};
allimgformats = {[imageFormats{:,1}], 'All Image Files'};
allmovformats = {[movieFormats{:,1}], 'All Movie Files'};
allbioformats = {[bioFormats{:,1}], 'All Raw- and Bio-Formats'};

% full fileformats cell
allFormatsList = [...
    {'*.*', 'All files'};...
    allformats;...
    allimgformats;...
    allmovformats;...
    allbioformats;...
    imageFormats;...
    movieFormats;...
    bioFormats;...
    specialFormats...
    ];

% Create cell array with isolated formats string
imageFormats = {};
imgcompr = strrep(imgcompr,';','');
imgcompr = strrep(imgcompr,'.','');
idx = [find(ismember(imgcompr,'*')) length(imgcompr)+1];
for i = 1:length(idx)-1
    imageFormats{i} = imgcompr(idx(i)+1:idx(i+1)-1);
end

% Create cell array with isolated formats string
movieFormats = {};
movcompr = strrep(movcompr,';','');
movcompr = strrep(movcompr,'.','');
idx = [find(ismember(movcompr,'*')) length(movcompr)+1];
for i = 1:length(idx)-1
    movieFormats{i} = movcompr(idx(i)+1:idx(i+1)-1);
end

% Create cell array with isolated formats string
bioFormats = {};
biocompr = strrep(biocompr,';','');
biocompr = strrep(biocompr,'.','');
idx = [find(ismember(biocompr,'*')) length(biocompr)+1];
for i = 1:length(idx)-1
    bioFormats{i} = biocompr(idx(i)+1:idx(i+1)-1);
end

% Create cell array with isolated formats string
specialFormats = {};
specompr = strrep(specompr,';','');
specompr = strrep(specompr,'.','');
idx = [find(ismember(specompr,'*')) length(specompr)+1];
for i = 1:length(idx)-1
    specialFormats{i} = specompr(idx(i)+1:idx(i+1)-1);
end

%% Old syntax

% if ismac
%     movformats = {'avi' 'mj2' 'mpg' 'mp4' 'm4v' 'mov' 'fits' 'fts' 'sif' 'spe'};
%     fileformats = {['*.avi;*.mj2;*.mpg;*.mp4;*.m4v;*.mov'...
%         '*.xwd;*.tif;*.tiff;*.spe;*.sif;*.ras;*.ppm;*.ppn;*.png;*.pgm;*.pcx;'...
%         '*.pbm;*.jpg;*.jpeg;*.jpf;*.jpx;*.jp2;*.j2c;*.j2k;*.ico;*.hdf;*.gif;'...
%         '*.fts;*.fits;*.cur;*.bmp'], 'All Image and Movie Files';...
%         ['*.xwd;*.tif;*.tiff;*.spe;*.sif;*.ras;*.ppm;*.ppn;*.png;*.pgm;*.pcx;'...
%         '*.pbm;*.jpg;*.jpeg;*.jpf;*.jpx;*.jp2;*.j2c;*.j2k;*.ico;*.hdf;*.gif;'...
%         '*.fts;*.fits;*.cur;*.bmp'], 'All Image Files';...
%         '*.avi;*.mj2;*.mpg;*.mp4;*.m4v;*.mov', 'All Movie Files';...
%         '*.bmp', 'Windows Bitmap';...
%         '*.cur', 'Windows Cursor resources';...
%         '*.fts;*.fits', 'Flexible Image Transport System';...
%         '*.sif', 'Andor Camera File';...
%         '*.spe', 'Princeton Instruments File v2+';...
%         '*.gif', 'Graphics Interchange Format';...
%         '*.hdf', 'Hierarchical Data Format';...
%         '*.ico', 'Windows Icon Resource';...
%         '*.jpf;*.jpx;*.jp2;*.j2c;*.j2k', 'JPEG 2000';...
%         '*.jpg;*.jpeg', 'Joint Photographic Experts Group';...
%         '*.pbm', 'Portable Bitmap';...
%         '*.pcx', 'Windows Paintbrush';...
%         '*.pgm', 'Portable Graymap';...
%         '*.png', 'Portable Network Graphics';...
%         '*.pnm', 'Portable Any Map';...
%         '*.ppm', 'Portable Pixmap';...
%         '*.ras', 'Sun Raster';...
%         '*.tif;*.tiff', 'Tagged Image File Format';...
%         '*.xwd', 'X Windows Dump';...
%         '*.avi', 'AVI file';...
%         '*.mj2', 'Motion JPEG 2000';...
%         '*.mpg', 'MPEG-1';...
%         '*.mp4;*.m4v', 'MPEG-4';...
%         '*.mov', 'Apple Quicktime Movie';...
%         '*.avi', 'AVI file';...
%         '*.mj2', 'Motion JPEG 2000';...
%         '*.mpg', 'MPEG-1';...
%         '*.mp4;*.m4v', 'MPEG-4';...
%         '*.mov', 'Apple Quicktime Movie';...
%         '*.*', 'All files'};
%         
% else
%     movformats = {'avi' 'mj2' 'mpg' 'wmv' 'asf' 'asx' 'mp4' 'm4v' 'mov' 'fits' 'fts' 'sif' 'spe'};
%     fileformats = {['*.avi;*.mj2;*.mpg;*.wmv;*.asf;*.asx;*.mp4;*.m4v;*.mov'...
%         '*.xwd;*.tif;*.tiff;*.spe;*.sif;*.ras;*.ppm;*.ppn;*.png;*.pgm;*.pcx;'...
%         '*.pbm;*.jpg;*.jpeg;*.jpf;*.jpx;*.jp2;*.j2c;*.j2k;*.ico;*.hdf;*.gif;'...
%         '*.fts;*.fits;*.cur;*.bmp'], 'All Image and Movie Files';...
%         ['*.xwd;*.tif;*.tiff;*.spe;*.sif;*.ras;*.ppm;*.ppn;*.png;*.pgm;*.pcx;'...
%         '*.pbm;*.jpg;*.jpeg;*.jpf;*.jpx;*.jp2;*.j2c;*.j2k;*.ico;*.hdf;*.gif;'...
%         '*.fts;*.fits;*.cur;*.bmp'], 'All Image Files';...
%         '*.avi;*.mj2;*.mpg;*.wmv;*.asf;*.asx;*.mp4;*.m4v;*.mov', 'All Movie Files';...
%         '*.bmp', 'Windows Bitmap';...
%         '*.cur', 'Windows Cursor resources';...
%         '*.fts;*.fits', 'Flexible Image Transport System';...
%         '*.sif', 'Andor Camera File';...
%         '*.spe', 'Princeton Instruments File v2+';...
%         '*.gif', 'Graphics Interchange Format';...
%         '*.hdf', 'Hierarchical Data Format';...
%         '*.ico', 'Windows Icon Resource';...
%         '*.jpf;*.jpx;*.jp2;*.j2c;*.j2k', 'JPEG 2000';...
%         '*.jpg;*.jpeg', 'Joint Photographic Experts Group';...
%         '*.pbm', 'Portable Bitmap';...
%         '*.pcx', 'Windows Paintbrush';...
%         '*.pgm', 'Portable Graymap';...
%         '*.png', 'Portable Network Graphics';...
%         '*.pnm', 'Portable Any Map';...
%         '*.ppm', 'Portable Pixmap';...
%         '*.ras', 'Sun Raster';...
%         '*.tif;*.tiff', 'Tagged Image File Format';...
%         '*.xwd', 'X Windows Dump';...
%         '*.avi', 'AVI file';...
%         '*.mj2', 'Motion JPEG 2000';...
%         '*.mpg', 'MPEG-1';...
%         '*.mp4;*.m4v', 'MPEG-4';...
%         '*.mov', 'Apple Quicktime Movie';...
%         '*.avi', 'AVI file';...
%         '*.mj2', 'Motion JPEG 2000';...
%         '*.mpg', 'MPEG-1';...
%         '*.wmv;*.asf;*.asx', 'Windows Media Video';...
%         '*.mp4;*.m4v', 'MPEG-4';...
%         '*.mov', 'Apple Quicktime Movie';...
%         '*.*', 'All files'};
% end
% 
% % Special image format readers
% specialformats = {'fits' 'fts' 'spe' 'sif'};
