function mainhandles = createGridFlex(mainhandles)
% Creates the resizable GUI elements in the main window. The resize
% function is mainResizeFcn.m
%
%    Input:
%     mainhandles   - handles structure of the main window
%
%    Output:
%     mainhandles   - ..
%

% --- Copyrights (C) ---
%
% This file is part of:
% iSMS - Single-molecule FRET microscopy software
% Copyright (C) Aarhus University, @ V. Birkedal Lab
% <http://isms.au.dk>
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     The GNU General Public License is found at
%     <http://www.gnu.org/licenses/gpl.html>.

%% Initialize

% Put a layout in the panel 
HBoxFlex = uiextras.HBoxFlex( 'Parent', mainhandles.gridflexPanel, ...
    'Units', 'Normalized', 'Position', [0 0 1 1], ...
    'Spacing', 5 );

% Color definitions
backgrColor = get(mainhandles.figure1,'Color'); % Background color
purpleColor = [2*101/255 2*90/255 1.5*159/255]; 
grayColor = [0.88 0.88 0.88];
whiteColor = [1 1 1];
lightblueColor = [0.75 0.9 1];
lightblueColor2 = [0.80 0.92 0.99];
lightblueColor3 = [0.90 0.94 0.99];
orangeColor = [255/255 229/255 11/255];

%% Left side of GUI

VBoxFlexLeft = uiextras.VBoxFlex( 'Parent', HBoxFlex, ...
    'Units', 'Normalized', 'Position', [0 0 1 1], ...
    'Spacing', 5 );

% Top left part
HBoxFlexTopLeft = uiextras.HBoxFlex( 'Parent', VBoxFlexLeft, ...
    'Units', 'Normalized', 'Position', [0 0 1 1], ...
    'Spacing', 5 );

% Files listbox
setappdata(0,'tooltipMenuString', 'Rename data')
fileslistboxBoxPanel = uiextras.BoxPanel( ...
    'Parent', HBoxFlexTopLeft,...
    'Title', 'Files ',...
    'BackgroundColor','black',...
    'MenuFcn', {@filespanelMenuFcn, mainhandles.figure1},...
    'TitleColor', lightblueColor2);
mainhandles.FilesListbox = uicontrol(...
    'Parent', fileslistboxBoxPanel,...
    'Style', 'listbox',...
    'String', '',...
    'units', 'normalized',...
    'Tag', 'FilesListbox',...
    'Position', [0 0 1 1],...
    'BackgroundColor', 'white',...
    'Interruptible', 'off',...
    'Callback', {@filesListboxCallback, mainhandles.figure1});

% Frames listbox
setappdata(0,'tooltipMenuString', 'Settings for selected menu item')
frameslistboxBoxPanel = uiextras.BoxPanel( ...
    'Parent', HBoxFlexTopLeft,...
    'Title', 'Frames ',...
    'BackgroundColor','black',...
    'MenuFcn', {@framesMenuFcn, mainhandles.figure1},...
    'TitleColor', lightblueColor2);
%     'HelpFcn', {@framesHelpFcn, mainhandles.figure1},...
mainhandles.FramesListbox = uicontrol(...
    'Parent', frameslistboxBoxPanel,...
    'Style', 'listbox',...
    'String', '',...
    'units', 'normalized',...
    'Tag', 'FramesListbox',...
    'Position', [0 0 1 1],...
    'BackgroundColor', 'white',...
    'Interruptible', 'off',...
    'Callback',{@frameListboxCallback, mainhandles.figure1});

% Peakfinderpanel
setappdata(0,'tooltipMenuString', 'Advanced settings for peak finder')
setappdata(0,'saveMenuString', 'Set these thresholds as default')
peakfinderBoxPanel = uiextras.BoxPanel( ...
    'Parent', HBoxFlexTopLeft,...
    'Title', 'Peak finder ',...
    'SaveFcn', {@savepeakthresDefaultsMenuFcn, mainhandles.figure1},...
    'MenuFcn', {@peakfinderMenuFcn, mainhandles.figure1},...
    'HelpFcn', {@panelHelpFcn, 'http://isms.au.dk/documentation/find-fret-pairs/'},...
    'TitleColor', lightblueColor2);
%     'DockFcn', {@dockFcn, mainhandles.figure1, 'peakfinder'},...
uipanelPeakfinder = uipanel(...
    'Parent', peakfinderBoxPanel,...
    'Units', 'normalized',...
    'Position', [0 0 1 1]);,...
%     'ResizeFcn', {@peakfinderResizeFcn, mainhandles.figure1});
mainhandles.DPeakFinderTextbox = uicontrol(...
    'Parent', uipanelPeakfinder,...
    'Style', 'Text',...
    'Tag', 'DPeakFinderTextbox',...
    'HorizontalAlignment', 'left',...
    'Units', 'normalized',...
    'String', 'D: ');
mainhandles.APeakFinderTextbox = uicontrol(...
    'Parent', uipanelPeakfinder,...
    'Style', 'Text',...
    'Tag', 'APeakFinderTextbox',...
    'HorizontalAlignment', 'left',...
    'Units', 'normalized',...
    'String', 'A: ');
mainhandles.DPeakSlider = uicontrol(...
    'Parent', uipanelPeakfinder,...
    'Style', 'slider',...
    'Interruptible', 'off',...
    'Tag', 'DPeakSlider',...
    'Units', 'normalized',...
    'BusyAction', 'cancel',...
    'TooltipString', 'Set number of (most intense) donor peaks',...
    'Callback', {@DPeakSliderCallback, mainhandles.figure1});
mainhandles.APeakSlider = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','slider',...
    'Interruptible','off',...
    'Tag','APeakSlider',...
    'Units', 'normalized',...
    'BusyAction', 'cancel',...
    'TooltipString','Set number of (most intense) acceptor peaks',...
    'Callback',{@APeakSliderCallback, mainhandles.figure1} );
mainhandles.DPeakCounter = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'Tag','DPeakCounter',...
    'HorizontalAlignment', 'left',...
    'Units', 'normalized',...
    'String', '0');
mainhandles.APeakCounter = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'Tag','APeakCounter',...
    'HorizontalAlignment', 'left',...
    'Units', 'normalized',...
    'String', '0');
mainhandles.EPeakCounterTextbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'Tag','EPeakCounterTextbox',...
    'HorizontalAlignment', 'left',...
    'Units', 'normalized',...
    'String', 'Pairs: ');
mainhandles.EPeakCounter = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'HorizontalAlignment', 'left',...
    'Tag','EPeakCounter',...
    'Units', 'normalized',...
    'String', '0');
mainhandles.PeakfinderThresholdTextbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'HorizontalAlignment', 'left',...
    'Tag','PeakfinderThresholdTextbox',...
    'Units', 'normalized',...
    'String', 'Peak thresholds /counts:');
mainhandles.DPeakfinderThresholdTextbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'HorizontalAlignment', 'left',...
    'Tag','DPeakfinderThresholdTextbox',...
    'Units', 'normalized',...
    'String', 'D: ');
mainhandles.APeakfinderThresholdTextbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Text',...
    'HorizontalAlignment', 'left',...
    'Tag','APeakfinderThresholdTextbox',...
    'Units', 'normalized',...
    'String', 'A: ');
mainhandles.DPeakfinderThresholdEditbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Edit',...
    'HorizontalAlignment', 'left',...
    'Tag','DPeakfinderThresholdEditbox',...
    'Units', 'normalized',...
    'Callback', {@peaktresholdEditboxCallback, mainhandles.figure1},...
    'HorizontalAlignment', 'right',...
    'BackgroundColor', 'white',...
    'String', '');
mainhandles.APeakfinderThresholdEditbox = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Edit',...
    'HorizontalAlignment', 'left',...
    'Tag','APeakfinderThresholdEditbox',...
    'Units', 'normalized',...
    'Callback', {@peaktresholdEditboxCallback, mainhandles.figure1},...
    'HorizontalAlignment', 'right',...
    'BackgroundColor', 'white',...
    'String', '');
mainhandles.runpeakfinderPushbutton = uicontrol(...
    'Parent',uipanelPeakfinder,...
    'Style','Pushbutton',...
    'HorizontalAlignment', 'left',...
    'Tag','runpeakfinderPushbutton',...
    'Units', 'normalized',...
    'Interruptible', 'off',...
    'Callback', {@peakfinderPushbuttonCallback, mainhandles.figure1},...
    'String', ' Run ');

% Raw image axes
setappdata(0,'tooltipMenuString', 'Settings for ROI auto-alignment')
setappdata(0,'tooltipMenu2String', 'Fine-adjust ROI positions')
setappdata(0,'tooltipMenu3String', 'Image settings')
setappdata(0,'tooltipRunString', 'Auto-align ROIs')
rawimageBoxPanel = uiextras.BoxPanel( ...
    'Parent', VBoxFlexLeft,...
    'Title', 'Raw data ',...
    'BackgroundColor','black',...
    'MenuFcn', {@rawpanelMenuFcn, mainhandles.figure1},...
    'Menu2Fcn', {@rawpanelMenu2Fcn, mainhandles.figure1},...
    'Menu3Fcn', {@rawpanelMenu3Fcn, mainhandles.figure1},...
    'HelpFcn', {@panelHelpFcn, 'http://isms.au.dk/documentation/align-emission-channels/'},...
    'RunFcn', {@rawpanelRunFcn, mainhandles.figure1},...
    'TitleColor', grayColor);
uipanelRAW = uipanel(...
    'Parent', rawimageBoxPanel,...
    'Units', 'normalized',...
    'Position', [0 0 1 0.9]);

% Raw image 
uipanelRawimage = uipanel(...
    'Parent', uipanelRAW,...
    'BorderType', 'none',...
    'Units', 'normalized',...
    'BackgroundColor','Black',...
    'Position', [0 0 1 0.9],...
    'BackgroundColor', 'black');%,...

mainhandles.rawimage = axes(...
    'Parent', uipanelRawimage,...
    'Tag', 'rawimage',...
    'Color', 'black',...
    'units', 'normalized',...
    'OuterPosition', [-0.01 -0.03 1.04 .99]);
%     'OuterPosition', [-0.01 -0.01 1.04 1.04]);

% Top bar
uipanelRAWtop = uipanel(...
    'Parent', uipanelRawimage,...
    'Units', 'normalized',...
    'BorderType', 'none',...
    'Units', 'normalized',...
    'Position', [0 0.9 1 0.1],...
    'BackgroundColor', 'black');
%     'ResizeFcn', @RAWtopbarResizeFcn,...
% Frameslider axes
mainhandles.rawframesliderAxes = axes(... 
    'Parent', uipanelRAWtop,...
    'Tag', 'rawframesliderAxes',...
    'Box', 'on',...
    'Color', [1 1 1],...
    'units', 'normalized');
% Frame textbox
mainhandles.rawframesliderTextbox = uicontrol(...
    'Style', 'text',...
    'Parent', uipanelRAWtop,...
    'Tag', 'rawframesliderTextbox',...
    'BackgroundColor', get(uipanelRAWtop,'BackgroundColor'),...
    'ForegroundColor', abs([1 1 1]-get(uipanelRAWtop,'BackgroundColor')),...
    'String', 'Frame slider',...
    'HorizontalAlignment', 'left',...
    'units', 'normalized');
% Contrastslider
mainhandles.rawcontrastSliderAx = axes(... 
    'Parent', uipanelRAWtop,...
    'Tag', 'rawcontrastSliderAx',...
    'Box', 'on',...
    'Color', [1 1 1],...
    'units', 'normalized');
% Frame textbox
mainhandles.rawcontrastTextbox = uicontrol(...
    'Style', 'text',...
    'Parent', uipanelRAWtop,...
    'Tag', 'rawcontrastTextbox',...
    'BackgroundColor', get(uipanelRAWtop,'BackgroundColor'),...
    'ForegroundColor', abs([1 1 1]-get(uipanelRAWtop,'BackgroundColor')),...
    'String', 'Contrast: ',...
    'HorizontalAlignment', 'right',...
    'units', 'normalized');

% Message board
mboardBoxPanel = uiextras.BoxPanel( ...
    'Parent', VBoxFlexLeft,...
    'Title', 'Message board ',...
    'TitleColor', grayColor,...
    'DockFcn', {@dockFcn, mainhandles.figure1, 'mboard'} );

mainhandles.mboard = uicontrol(...
    'Parent', mboardBoxPanel,...
    'Style', 'edit',...
    'max', 2,...
    'BackgroundColor','white',...
    'Tag', 'mboard',...
    'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'HorizontalAlignment', 'left');

%% Right side of GUI

VBoxFlexRight = uiextras.VBoxFlex( 'Parent', HBoxFlex, ...
    'Units', 'Normalized', 'Position', [0 0 1 1], ...
    'Spacing', 5 );
% setappdata(0,'tooltipMenuString', 'Settings for contrast slider')
setappdata(0,'tooltipROIchannelString', 'Shift emission channel shown in image')
ROIimageBoxPanel = uiextras.BoxPanel( ...
    'Parent', VBoxFlexRight,...
    'Title', 'Emission channel overlay ',...
    'ROIchannelFcn', {@ROIpanelChannelFcn, mainhandles.figure1},...
    'TitleColor', grayColor);
uipanelROI = uipanel(...
    'Parent', ROIimageBoxPanel,...
    'Units', 'normalized',...
    'Position', [0 0 1 0.9]);

% ROI image 
uipanelROIimage = uipanel(...
    'Parent', uipanelROI,...
    'BorderType', 'none',...
    'Units', 'normalized',...
    'BackgroundColor','Black',...
    'Position', [0 0 1 0.9],...
    'BackgroundColor', 'black');%,...
mainhandles.ROIimage = axes(...
    'Parent', uipanelROIimage,...
    'Tag', 'ROIimage',...
    'Color', 'black',...
    'units', 'normalized',...
    'OuterPosition', [-0.06 -0.06 1.12 1.01]);

% Top bar
uipanelROItop = uipanel(...
    'Parent', uipanelROI,...
    'Units', 'normalized',...
    'BorderType', 'none',...
    'Units', 'normalized',...
    'Position', [0 0.9 1 0.1],...
    'BackgroundColor', 'black');
%     'ResizeFcn', @ROItopbarResizeFcn,...
% Frameslider axes
mainhandles.ROIframesliderAxes = axes(... 
    'Parent', uipanelROItop,...
    'Tag', 'ROIframesliderAxes',...
    'Box', 'on',...
    'Color', [1 1 1],...
    'units', 'normalized');
% Frame textbox
mainhandles.ROIframesliderTextbox = uicontrol(...
    'Style', 'text',...
    'Parent', uipanelROItop,...
    'Tag', 'ROIframesliderTextbox',...
    'BackgroundColor', get(uipanelROItop,'BackgroundColor'),...
    'ForegroundColor', abs([1 1 1]-get(uipanelROItop,'BackgroundColor')),...
    'String', 'Frame slider ',...
    'HorizontalAlignment', 'left',...
    'units', 'normalized');
% Contrastslider 1
mainhandles.redROIcontrastSliderAx = axes(... 
    'Parent', uipanelROItop,...
    'Tag', 'redROIcontrastSliderAx',...
    'Box', 'on',...
    'Color', [1 1 1],...
    'units', 'normalized');
% Red contrast textbox
mainhandles.redROIcontrastTextbox = uicontrol(...
    'Style', 'text',...
    'Parent', uipanelROItop,...
    'Tag', 'redROIcontrastTextbox',...
    'BackgroundColor', get(uipanelROItop,'BackgroundColor'),...
    'ForegroundColor', abs([1 1 1]-get(uipanelROItop,'BackgroundColor')),...
    'String', 'Red contrast ',...
    'HorizontalAlignment', 'right',...
    'units', 'normalized');
% Contrastslider 1
mainhandles.greenROIcontrastSliderAx = axes(... 
    'Parent', uipanelROItop,...
    'Tag', 'greenROIcontrastSliderAx',...
    'Box', 'on',...
    'Color', [1 1 1],...
    'units', 'normalized');
% Red contrast textbox
mainhandles.greenROIcontrastTextbox = uicontrol(...
    'Style', 'text',...
    'Parent', uipanelROItop,...
    'Tag', 'greenROIcontrastTextbox',...
    'BackgroundColor', get(uipanelROItop,'BackgroundColor'),...
    'ForegroundColor', abs([1 1 1]-get(uipanelROItop,'BackgroundColor')),...
    'String', 'Green contrast ',...
    'HorizontalAlignment', 'right',...
    'units', 'normalized');

% Remove temporary appdata
rmappdata(0,'tooltipMenuString')
rmappdata(0,'tooltipRunString')

% Store flex grids and panels in handles structure
% Left side
mainhandles.VBoxFlexLeft = VBoxFlexLeft;
mainhandles.HBoxFlexTopLeft = HBoxFlexTopLeft;
mainhandles.peakfinderBoxPanel = peakfinderBoxPanel;
mainhandles.uipanelPeakfinder = uipanelPeakfinder;
mainhandles.uipanelRAW = uipanelRAW;
mainhandles.uipanelRawimage = uipanelRawimage;
mainhandles.uipanelRAWtop = uipanelRAWtop;
mainhandles.mboardBoxPanel = mboardBoxPanel;

% Right side
mainhandles.uipanelROI = uipanelROI;
mainhandles.uipanelROIimage = uipanelROIimage;
mainhandles.uipanelROItop = uipanelROItop;
mainhandles.ROIimageBoxPanel = ROIimageBoxPanel;

%% Element sizes

HBoxFlex.Sizes = [-1 -1]; % Column sizes
VBoxFlexLeft.Sizes = [-3 -5.5 -1.5]; % Row sizes
HBoxFlexTopLeft.Sizes = [-5 -2 -4]; % Column sizes
% VBoxFlexRight.Sizes = [-4 -1]; % Row sizes

% Update handles
updatemainhandles(mainhandles)

% Update some GUI sizes
% From R2014b this is not run here
% peakfinderResizeFcn([],[],mainhandles.figure1) 
RAWtopbarResizeFcn(uipanelRAWtop,[])
ROItopbarResizeFcn(uipanelROItop,[])

end

function dockFcn( hObject, eventData, mainhandle, whichpanel )
% Get box panel object
try  mainhandles = guidata(mainhandle);
    [boxPanel, parentFlex] = getwhichpanel();
catch err
    mainhandle = getappdata(0,'mainhandle');
    mainhandles = guidata(mainhandle);
    [boxPanel, parentFlex] = getwhichpanel();
end

% Set the flag
boxPanel.IsDocked = ~boxPanel.IsDocked;
if boxPanel.IsDocked
    % Put it back into the layout
    newfig = get( boxPanel, 'Parent' );
    set( boxPanel, 'Parent', parentFlex );
    delete( newfig );
else
    % Take it out of the layout
    pos = getpixelposition( boxPanel );
    newfig = figure( ...
        'Name', get( boxPanel, 'Title' ), ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'CloseRequestFcn', { @dockFcn, mainhandle, whichpanel} );
    updatelogo(newfig)
    figpos = get( newfig, 'Position' );
    set( newfig, 'Position', [figpos(1,1:2), pos(1,3:4)] );
    set( boxPanel, 'Parent', newfig, ...
        'Units', 'Normalized', ...
        'Position', [0 0 1 1] );
end

    function [boxPanel, parentFlex] = getwhichpanel(~)
        % Returns relevant handles to current object
        if strcmpi(whichpanel,'mboard')
            boxPanel = mainhandles.mboardBoxPanel;
            parentFlex =  mainhandles.VBoxFlexLeft;

        elseif strcmpi(whichpanel, 'peakfinder')
            boxPanel = mainhandles.peakfinderBoxPanel;
            parentFlex = mainhandles.HBoxFlexTopLeft;
        end
    end

end
